### ISSUE TITLE
XLSX

### ISSUE THREAD

**Issue by lanzosuarez** [ashishsantikari/excel-export-angular2#1]
Why is it the xlsx was commented out?

**Comment by lanzosuarez** [comment]
It is all good now. an error "DUPLICATE SHEET NAME IS BEING THROWN"
Can i ask how can i add an additional cell for title and maybe date?

**Comment by raogowtham** [comment]
@lanzosuarez I am getting **(38,13): Cannot find namespace 'XLSX'** in exporttoexcel.component.ts in line no 38. How are u able to resolve it ??

**Comment by lanzosuarez** [comment]
You just need to install xlxs. npm install --save xlsx
 then uncomment the import statement at the top. You also need to change IWorkBook to Workbook, and remove cellStyles, in XLSX.write

**Comment by mittalvaibhav** [comment]
Hi,
After doing above steps, I am still getting below error:
ERROR in <localpath>/excel-export-angular2-master/src/app/exporttoexcel.component/exporttoexcel.component.ts (38,18): Module '"<localpath>/excel-export-angular2-master/node_modules/@types/xlsx/index"' has no exported member 'WorkBook'

**Comment by vijayUV** [comment]
@mittalvaibhav this is a common issue, probably because of cache. stop the compiler and rebuild it should work. It worked like a gem for me.
@lanzosuarez Many thanks for the XSLS issue resolution.
@ashishsantikari Man you are a life saver.. thank for this post.

**Comment by sadiqcs47** [comment]
Hi @lanzosuarez @mittalvaibhav Im stil getting the cannot find module in the below line
 import * as XLSX from 'xlsx'; Please help regarding this. Same for file saver too 
import * as FileSaver from 'file-saver';

**Comment by ashishsantikari** [comment]
Sorry guys, I was away from GitHub for a long long time. Anyway, do you still need support or all the issues that you mentioned are fixed?

**Comment by ashishsantikari** [comment]
This issue has been fixed with latest release of xlsx, it's types and migration of angular to v8. Closing this issue.
