### ISSUE TITLE
Cannot find namespace 'XLSX'

### ISSUE THREAD

**Issue by raogowtham** [ashishsantikari/excel-export-angular2#2]
I am getting Cannot find namespace XLSX error when i give 
npm  run start

**Comment by vijayUV** [comment]
I am also getting the same issue "Cannot find namespace XLSX error" in angular cli

**Comment by krisha23** [comment]
@vijayUV @raogowtham I am also stuck here. Did you find a solution?

**Comment by ashishsantikari** [comment]
Closing this issue as issue has been fixed with latest releases of angular, xlsx and @types/xlsx
